name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    env:
      SCCACHE_GHA_ENABLED: "false" # sccache is deprecated since April 15, 2025. See https://gh.io/gha-cache-sunset. 

    strategy:
      matrix:
        os: [windows-latest]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - if: matrix.os == 'windows-latest'
      name: Build Windows
      run: |
        mkdir ${{ github.workspace }}/release
        cmake -A Win32 -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }} -DOUTDIR=${{ github.workspace }}/release
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }} --target csgo srcds csgo_gc

    - name: Package
      shell: bash
      run: |
        cp $GITHUB_WORKSPACE/README.md $GITHUB_WORKSPACE/release/
        cp $GITHUB_WORKSPACE/LICENSE $GITHUB_WORKSPACE/release/
        cp $GITHUB_WORKSPACE/examples/config.txt $GITHUB_WORKSPACE/release/csgo_gc/
        cp $GITHUB_WORKSPACE/examples/inventory.txt $GITHUB_WORKSPACE/release/csgo_gc/
        cp $GITHUB_WORKSPACE/examples/unusual_loot_lists.txt $GITHUB_WORKSPACE/release/csgo_gc/

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: csgo_gc-${{ matrix.os }}
        path: ${{ github.workspace }}/release
